version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    networks:
      - app_network

  scrapy:
    build: .
    container_name: scrapy
    command: scrapy runspider scrapy_app/spiders/sreality_spider.py
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - app_network

  app:
    container_name: app
    build: .
    command: python http_server/app.py
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
